# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build the app
    cmds:
    - GOFLAGS=-mod=mod go build -o bin/go-rest-api internal/main.go

    # Windows 32 bits
    #$ GOOS=windows GOARCH=386 go build -o bin/go-rest-api-win-386 internal/main.go

    # Windows 64 bits
    #$ GOOS=windows GOARCH=amd64 go build -o bin/go-rest-api-win-64 internal/main.go

    # Linux 32 bits
    #$ GOOS=linux GOARCH=386 go build -o bin/go-rest-api-linux-386 internal/main.go

    # Linux 64 bits
    #$ GOOS=linux GOARCH=amd64 go build -o bin/go-rest-api-linux-64 internal/main.go

    # MacOS 32 bits
    #$ GOOS=darwin GOARCH=386 go build -o bin/go-rest-api-darwin-386 internal/main.go

    # MacOS 64 bits
    #$ GOOS=darwin GOARCH=amd64 go build -o bin/go-rest-api-darwin-64 internal/main.go

    # MacOS 64 bits for M1 chip
    #$ GOOS=darwin GOARCH=arm64 go build -o bin/go-rest-api-darwin-arm64 internal/main.go

  run:
    desc: Run the app
    cmds:
    - GOFLAGS=-mod=mod go run internal/main.go

  swagger.gen:
    desc: Generate Go code
    cmds:
    - GOFLAGS=-mod=mod go generate github.com/f-colombo/learning-go-by-examples/go-rest-api/internal github.com/f-colombo/learning-go-by-examples/go-rest-api/pkg/swagger

  swagger.validate:
    desc: Validate swagger
    cmds:
    - swagger validate pkg/swagger/swagger.yml

  swagger.doc:
    desc: Doc for swagger
    cmds:
    - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html
